server.port=8081
# spring.application.name= user-service

# PostgreSQL JDBC URL (change database name as needed)
spring.datasource.url=jdbc:postgresql://localhost:5432/fitness

# PostgreSQL DB credentials
spring.datasource.username=postgres
spring.datasource.password=dbc

# Hibernate dialect for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Automatically create or update tables
spring.jpa.hibernate.ddl-auto=update

# Optional: Show SQL queries in the console (good for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/